== Day 5: Hydrothermal Venture

TIP: Find the full puzzle https://adventofcode.com/2021/day/5

=== Problem Star 1
[quote]
....
You come across a field of hydrothermal vents on the ocean floor! These vents constantly produce large, opaque clouds, so it would be best to avoid them if possible.

They tend to form in lines; the submarine helpfully produces a list of nearby lines of vents (your puzzle input) for you to review. For example:
....
=== Test
[source,rust,numbered]
....
include::src/lib.rs[tag=testdata]
....
==== Testcase
[quote]
....
To avoid the most dangerous areas, you need to determine the number of points where at least two lines overlap. In the above example, this is anywhere in the diagram with a 2 or larger - a total of 5 points.
....
[source,rust,numbered]
....
include::src/lib.rs[tag=test1]
....

=== Solution

The diagram (here it is called Board, because the class was allready created yesterday :-) ) was implemented.

[source,rust,numbered]
....
include::src/util.rs[tag=board]
....

Finally, the horizontal and vertical lines were simply drawn on the board. Ohhh. There are also lines that go from bottom to top and from left to right. 
[source,rust,numbered]
....
include::src/util.rs[tag=horizontal-vertical]
....
=== Problem Star 2
Same problem and solution, but consider also diagonals.

==== Testcase
[quote]
....
You still need to determine the number of points where at least two lines overlap. In the above example, this is still anywhere in the diagram with a 2 or larger - now a total of 12 points.
....
[source,rust,numbered]
....
include::src/lib.rs[tag=test2]
....

=== Solution
[source,rust,numbered]
....
include::src/util.rs[tag=diagonal]
....