== Day 12: Passage Pathing ==

https://rust-lang.org[Rust] solution to https://adventofcode.com/2021/day/12[AoC|2021|12].

=== Solution ===

Again a kind of breadth first traversal and the first day in the 2021 edition where my solution takes significant time (more than a couple of ms) to compute. After some optimizations, I am now down to about 40ms for part 2.

==== Data Structure for the Cave Map ====

To start, I parse the input into a struct ``CaveMap`` (see comments in code for details):

[source,rust,numbered]
----
include::src/lib.rs[tags=cavemap]
----

In my initial implementation, I used a ``BTreeMap`` to map cave names to adjacent names. In the current version, I use cave IDs instead, which are the addresses to the fields in the CaveMap structure. This reduced the runtime by about 25%.

==== Searching for Paths ====

The general soluton idea is to do a (breadth first) traversal on a graph of all possible paths through the cave (graph nodes are paths, not caves):

. Push a path consisting of the ``start`` cave only to the queue
. Pop a path from the queue, and look at all adjacent caves of the last cave on the path
** if the adjacent cave is ``start``, ignore it
** if the adjacent cave is ``end``, the path is complete; increase the unqiue path counter
** if the adjacent cave is a large cave, append it to the path and push the extended path to the queue
** if the adjacent cave is a small cave, append it to the path and push the extended path to the queue if
*** the small cave is not yet on the path (part 1 & 2) or 
*** the small cave is already on the path and no small cave is on the path twice yet (part 2 only)
. Repeat step 2 until queue is empty

[source,rust,numbered]
----
include::src/lib.rs[tags=get_path_count]
----

Initially, I used ``Vec``s to represent paths. I copied the entire path and pushed new elements to the copies. In the current version, I use kind of a linked list (each path element has a reference to the parent element). Since linked lists are something that does not go very well with Rust's ownership and borrowing system (or maybe I just don't know how to do that properly), I keep a ``Vec`` of all path elements. Each path element is a tuple of a cave ID and and a parent pointer, which points to the parent path element in that ``Vec``. Because the start of a path has no parent, the parent pointer is wrapped in an ``Option``. This optimization reduced the runtime by about 75%.

The check whether a cave ID is contained in a path is implemented as follows:

[source,rust,numbered]
----
include::src/lib.rs[tags=contains]
----

=== Tests ===

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
