==  Day 3: xxx  ==

This solution is written in Kotlin.

The original puzzle can be found at https://adventofcode.com/2021/day/3

For execution enter _kotlin day2102_1_2.kts_ in the command line.

=== First Star

How does it work: +

Inside function _dive_ the puzzle input will be read line by line and split into the instruction part _instruction[0]_ and the value _instruction[1]_. The varibles _depth_ and _horizontal_ are increased or decreased within a if/else instruction according to their instructions. After going through the complete input file _depth_ multiplied by _horizontal_ is returned
[source, kotlin, numbered]
....
include::day2103_1_2.kts[tags=dive_1]
....


=== Second Star

How does it work: +

Inside function _dive_2_ the puzzle input will be read line by line and split into the instruction part _instruction[0]_ and the value _instruction[1]_. The varibles _depth_, _horizontal_ and _aim_ are increased or decreased within a if/else instruction according to their instructions. After going through the complete input file _depth_ multiplied by _horizontal_ is returned
[source, kotlin, numbered]
....
include::day2103_1_2.kts[tags=dive_2]
....

At the end, both solutions are printed out. 
[source, kotlin, numbered]
....
include::day2103_1_2.kts[tags=output]
....