==  Day 4: Lanternfish

This solution is written in Groovy.

The original puzzle can be found at https://adventofcode.com/2021/day/6

The working example can be found here https://github.com/uniqueck/advent-of-code/tree/2021/groovy/src/main/groovy/io/uniqueck/aoc/day6[uniqueck / advent-of-code]

=== Today I learned

For performance fallback to simple data types is a good idea ;)

=== First Star + Second Star

I started to create a class representing the LanternFish and his behaviour, this worked well for Start 1, but for Star 2 this is a memory problem to spawn every time a new object of LanternFish.

So i switched back to array based approach. We have a array of datatype long to eliminate integer overflow errors.

So we iterate over the array and shift each entry to the left, until we reached the first position. For the first position we added the current count of fishes to position 6 (reseted age to 6 days) and the current count of zero day fishes as new borned fishes at position 8 (8 days).

[source, groovy, numbered]
----
include::Simulator.groovy[]
----

For the input processing we have to count all fishes based on the age of days to create the initialStock array.