++++
<style> 
    ul p, ol p, ul>li p, ol>li p { 
        line-height: 1.2;
        margin-top: 0; 
        margin-bottom: 0;
    }   
</style>
++++

== AoC21-13: Transparent Origami
https://adventofcode.com/2021/day/13

=== Info

Get code by setting dots on transparent paper and folding it.

* Star1 (*): How many visible dots on sheet after first fold

* Star2 (**): What 8 letters are visible after all folds

=== HowTo

Data is read from the file 'input<two-digit-day>.txt' line by line and prepocessed into sheet with '1' for dot and '0' for transparent, as well as list of folds.

* Star1: Iterate single fold and count visible dots.

* Star2: Iterate all folds and display the eight letter from the dots. Be careful to move the right lines - move in both directions from the folding line. Otherwise the output will be illegible...

=== Learned today

Took some time to find the error (garbled characters). Did not iterate from foldline first, but from the outside, leading to a pixel shift on some folds...

=== Source

[source, python]
....
include::solution.py[]  
....
