== Day 24: Arithmetic Logic Unit ==

https://rust-lang.org[Rust] solution to https://adventofcode.com/2021/day/24[AoC|2021|24].

I don't get the idea of today's puzzle. I essentially solved it manually. From my point of view, a well posed problem allows to implement a solution without looking at the puzzle input data and than compute a solution based on the puzzle input. For today's problem, I don't think there is a way to find a solution without analyzing the puzzle input.

I reverse engineered the MONAD (puzzle input) to figure out what actually happens. The content in variable z can essentially be interpreted as a stack od input digits with offsets. To add stack elements, the current content is multiplied with 26 (in case of my puzzle input) and than the next element is added. This constrains an element to be in the range 0 to 25 (inclusive). Since input digits are in the range 0 to 9 (inclusive), offsets shall be in the range 0 to 16 (inclusive).

The MONAD contains of 14 blocks (one for every input digit), which evaluate a condition and based on the outcome push a new element to the stack (the z variable).

In seven of the blocks, the condition evaluates to true independently of the input digit. In the remaining seven blocks, a new element is pushed to the stack if ``dX != dY + o``. For stack to be empty at the end and thus the variable ``z`` to equal zero, elements shall not be pushed to the stack, i.e., ``dX = dY + o``, where ``dX`` and ``dY`` are digits of the serial number to be checked and ``o >= 0`` is an offset.

For the equalities to be satisfied, ``dY >= 1`` and ``dY <= 9 - o`` need to be satisfied.

=== Solution ===

After I had the solution, I put into code what I did manually (so it might work for other inputs assuming they differ in the offsets only).

[source,rust,numbered]
----
include::src/lib.rs[tags=solution]
----

=== Traits, Index and implementation ===

I wanted to learn something today, so I implemented Instructions using structs, traits and enums. This allows to have all range checks done at compile time.

[source,rust,numbered]
----
include::src/lib.rs[tags=instructions]
----

=== Tests ===

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
