== Day 00: Hello World ==

It'll be another day of https://www.rust-lang.org/[Rust] solutions for the 2021 edition of 
https://adventofcode.com/2021[Advent of Code]

=== General structure ===

Generally, my solutions will contain a `src/main.rs` file which reads the input from `input.txt`, 
calls the solution functions and measures time.

The actual solution will be implemented in `src/lib.rs` file.

The `lib.rs` file also contains the tests in a separate submodule. I will use this for test-driven 
development, e.g., based on the examples given in the puzzles.

=== Run Solutions ===

Run solution with `cargo run --release`

Run tests with `cargo test` or `cargo test --release`

=== Personal Challenges ===

It is December 21st in the meantime. I got that far trying to 

* Keep the overall time for all solutions as small as possible (< 500ms would be great)
* Do not use anything but out of the box Rust

Let's see whether I can keep up with these constraints until the end.

=== Run all Solutions ===

My `day00` solution this year will run all my solutions. At this time, it looks as follows

[source,rust,numbered]
----
include::src/lib.rs[tags=solve]
----
