== Day 19: Beacon Scanner ==

https://rust-lang.org[Rust] solution to https://adventofcode.com/2021/day/19[AoC|2021|19].

The solution for today's puzzle takes ~60ms to complete in my current implementation (optimized from 30 seconds in the first version).

The key for these optimizations is to realize that distances between beacons are invariant under coordinate transformations and thus do as much as possible on the distances and only figure out the correct transformation late. I have to admit that I did not come up with this idea myself but had to look at other solutions. I took the idea from https://github.com/mogron[Moritz Gronbach].

=== Parts 1 & 2 ===

When reading the input, I create a distance map (``dists``) which -- for every beacon in a scanner's set -- creates a map with distances as keys and lists of beacons at that distance as values.

[source,rust,numbered]
----
include::src/lib.rs[tags=parse]
----

This is used in a ``check_overlap`` function, which first finds beacons in two scanner's (``self`` and ``other``) that have at least 12 distances to other scanners in common and stores a list of ``pairs`` of beacons that are potentially the same (a bit of extra thinking is required for the case that more than one beacon is at the same distance)

Using this list of ``pairs``, I then search for a matching transformation / offset to map at least 12 beacons in the two scanner's.

[source,rust,numbered]
----
include::src/lib.rs[tags=check_overlap]
----

The final piece of the solution is to walk through the scanners and check for overlaps until all scanners are settled. This is done by pushing settled scanners to a stack and then repeatedly popping a scanner from the stack and finding scanners with overlapping range to the settled one until everything is settled. While settling the scanners, the largest distance between any two scanners is stored and a list of unique beacons is populated.

[source,rust,numbered]
----
include::src/lib.rs[tags=solution]
----

=== Implementation details ===

Some details of the implementation include:

A ``Coord`` structure (including code to parse/print coordinates)

[source,rust,numbered]
----
include::src/lib.rs[tags=coordinate]
----

A list of valid transformations

[source,rust,numbered]
----
include::src/lib.rs[tags=trafos]
----

A ``Scanner`` structure (including code to parse/print scanners)

[source,rust,numbered]
----
include::src/lib.rs[tags=scanner]
----

The ``Scanner`` implementation includes a sanity check for overlapping regions:

[source,rust,numbered]
----
include::src/lib.rs[tags=sanity]
----

By default, the sanity check is switched off. It is enabled with the feature ``sanity-check``, i.e., if the puzzle is run with ``cargo run --release --features sanity-check``. For my puzzle input & the examples, the sanity check passes.

=== Tests ===

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
