name: GitHub Pages

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: chmod +x ./gradlew
      - name: fix config
        run: sed -i 's|site.contextPath=/$|site.contextPath=/aoc-2021/|g' src/site/jbake.properties
      - name: fix build.gradle
        run: sed -i 's|link:/gene|link:/aoc-2021/gene|g' build.gradle
      - name: generate site
        run: ./gradlew generateIndex bake --info --stacktrace
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/html5/site
